### ISSUE TITLE
Please update lesson or add IDE capability

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/oo-ruby-cli-data-gem-walkthrough-creating-a-cli-scraper-gem#2]
Cannot open url in browser through LEARN IDE terminal command.
<img width="875" alt="screen shot 2017-06-13 at 6 03 24 pm" src="https://user-images.githubusercontent.com/26909418/27108493-17bfc238-5063-11e7-992f-dd7248e0a597.png">

**Comment by curiositypaths** [comment]
Hi there,

If you would like to code-along with this video you would need to install a local development environment (http://help.learn.co/workflow-tips/local-environment/mac-osx-manual-environment-set-up-for-immersive-students). 

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
